#!/bin/bash

#curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET https://images-api.nasa.gov
#wget -O /tmp/NASA.jpg $URL
#sed -i 's#^\(wallpaper\s*=\s*\).*$#\1/tmp/NASA.jpg#' /home/david/.config/pcmanfm/LXDE/desktop-items-0.conf
#kwriteconfig --file plasma-desktop-appletsrc --group Containments --group 126 --group Wallpaper --group image --key wallpaper

echo -e "Copyright 2017 David Población Criado"
echo -e "Apache License, Version 2.0\n"
API_KEY="Z1an39TefCytrrClcLSxNGJDGwv09QLHD6zo74R8"
VERSION="1.0"
if [ ! -d "$HOME/.nasa-wallpaper/" ]; then
	mkdir $HOME/.nasa-wallpaper/
fi

if command -v jq >/dev/null 2>&1 ; then
    echo "jq found"    
else
    echo "ERROR: jq not found"
fi
if command -v wget >/dev/null 2>&1 ; then
    echo "wget found"    
else
    echo "ERROR: wget not found"
fi
if command -v curl >/dev/null 2>&1 ; then
    echo "curl found"    
else
    echo "ERROR: curl not found"
fi

while getopts 'd:k:c:p:P:y:Y:e:E:w:i:q:l:t:T: anrvh' opt; do
	case $opt in
		d)  DATE=$OPTARG
			DATE_Q="&date="$DATE;;

		k)	APIKEY=$OPTARG;;	

		c)	TMP=$OPTARG
			CENTER="&center="$TMP;;

		p)	TMP=$OPTARG
			PHOTOGRAPHER="&photographer="$TMP;;

		P)  TMP=$OPTARG
			SEC_CREATOR="&secondary_creator="$TMP;;

		y)	TMP=$OPTARG
			YEAR_S="&year_start="$TMP;;

		Y)	TMP=$OPTARG
			YEAR_E="&year_end="$TMP;;

		e)	TMP=$OPTARG
			EXPLANATION="&description="$TMP;;

		E)	TMP=$OPTARG
			S_EXPLANATION="&description_508="$TMP;;

		w)	TMP=$OPTARG
			KEYWORDS="&keywords="$TMP;;

		i)	TMP=$OPTARG
			NID="&nasa_id="$TMP;;

		q)	TMP=$OPTARG
			SEARCH="&q="$TMP;;

		l) 	TMP=$OPTARG
			LOCATION="&location="$TMP;;	

		t)	TMP=$OPTARG
			S_TITLE="&title="$TMP;;		

		T)	TARGET=$OPTARG;;

		a) 	APOD="https://api.nasa.gov/planetary/apod?api_key="						
			URL_APOD=$APOD$API_KEY$DATE_Q			
			#rm $HOME/.nasa-wallpaper/apod.json			
	
			curl -G $URL_APOD >> $HOME/.nasa-wallpaper/apod.json
			URL_APOD_FINAL=$(jq '.hdurl' $HOME/.nasa-wallpaper/apod.json)			
			TITULO=$(jq '.title' $HOME/.nasa-wallpaper/apod.json)
			DESCRIPCION=$(jq '.explanation' $HOME/.nasa-wallpaper/apod.json)
			COPYRIGHT=$(jq '.copyright' $HOME/.nasa-wallpaper/apod.json)
			FECHA=$(jq '.date' $HOME/.nasa-wallpaper/apod.json)
			
			temp="${URL_APOD_FINAL%\"}"			
			temp="${temp#\"}"
			wget -O $HOME/.nasa-wallpaper/$FECHA.jpg $temp
			
			echo -e "Title: $TITULO\n"
			echo -e "Explanation: $DESCRIPCION\n"
			echo -e "Copyright: $COPYRIGHT\n"
			
			rm $HOME/.nasa-wallpaper/apod.json

			case $TARGET in
				"gnome") gsettings set org.gnome.desktop.background picture-uri "$HOME/.nasa-wallpaper/$FECHA.jpg";;
				"cinnamon") gsettings set org.cinnamon.desktop.background picture-uri "$HOME/.nasa-wallpaper/$FECHA.jpg";;
				"lxde") pcmanfm --set-wallpaper=$HOME/.nasa-wallpaper/$FECHA.jpg;;
				"xfce") xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "$HOME/.nasa-wallpaper/$FECHA.jpg";;
				"mate") gsettings set org.mate.background picture-filename "$HOME/.nasa-wallpaper/$FECHA.jpg";;
			esac;;	

		n)	URL="https://images-api.nasa.gov/search?media_type=image"
			URL_NASA=$URL$SEARCH$NID$CENTER$PHOTOGRAPHER$YEAR_S$YEAR_E$EXPLANATION$KEYWORDS$LOCATION$S_CREATOR$S_EXPLANATION$S_TITLE
			#echo $URL_NASA
			
			curl -X GET $URL_NASA >> $HOME/.nasa-wallpaper/nasa.json			
			TOTAL=$(jq .collection.metadata.total_hits $HOME/.nasa-wallpaper/nasa.json)
			echo "Total results: $TOTAL"
			if ((TOTAL == 0))
			then
				echo "ERROR: There is not any image with this parameters :("
				exit 0
			fi
			if (($TOTAL < 7))
			then					
				NUM=$TOTAL
				((NUM--))
			else
				NUM=$[ ( $RANDOM % 100 )-1]
			fi			
			URL_NASA_METADATA=$(jq .collection.items[$NUM].href $HOME/.nasa-wallpaper/nasa.json)
			#echo $URL_NASA_METADATA						
			ID=$(jq .collection.items[$NUM].data[0].nasa_id $HOME/.nasa-wallpaper/nasa.json)
			TITULO=$(jq .collection.items[$NUM].data[0].title $HOME/.nasa-wallpaper/nasa.json)
			CENTRO=$(jq .collection.items[$NUM].data[0].center $HOME/.nasa-wallpaper/nasa.json)
			DESCRIPCION=$(jq .collection.items[$NUM].data[0].description $HOME/.nasa-wallpaper/nasa.json)
			FECHA=$(jq .collection.items[$NUM].data[0].date_created $HOME/.nasa-wallpaper/nasa.json)
			URL_NASA_METADATA="${URL_NASA_METADATA%\"}"
			URL_NASA_METADATA="${URL_NASA_METADATA#\"}"		
			
			curl -X GET $URL_NASA_METADATA >> $HOME/.nasa-wallpaper/collection.json
			URL_NASA_FINAL=$(jq '.[0]' $HOME/.nasa-wallpaper/collection.json)
			
			temp="${URL_NASA_FINAL%\"}"			
			temp="${temp#\"}"
			wget -O $HOME/.nasa-wallpaper/$ID.jpg $temp

			echo -e "Title: $TITULO\n"
			echo -e "Explanation: $DESCRIPCION\n"
			echo -e "Center: $CENTRO\n"
			echo -e "Date: $FECHA\n"
			echo -e "NASA ID: $ID\n"

			rm $HOME/.nasa-wallpaper/nasa.json
			rm $HOME/.nasa-wallpaper/collection.json

			case $TARGET in
				"gnome") gsettings set org.gnome.desktop.background picture-uri "$HOME/.nasa-wallpaper/$ID.jpg";;
				"cinnamon") gsettings set org.cinnamon.desktop.background picture-uri "$HOME/.nasa-wallpaper/$ID.jpg";;
				"lxde") pcmanfm --set-wallpaper=$HOME/.nasa-wallpaper/$ID.jpg;;
				"xfce") xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "$HOME/.nasa-wallpaper/$ID.jpg";;
				"mate") gsettings set org.mate.background picture-filename "$HOME/.nasa-wallpaper/$ID.jpg";;
			esac;;

		r)	rm 	$HOME/.nasa-wallpaper/*.jpg
			rm 	$HOME/.nasa-wallpaper/*.*;;

		v)	echo "$VERSION";;

		h)  	man /usr/share/man/man1/nasa-wallpaper.1.gz;;
			
		*) 	exit 1;;
	esac
done
